name: Copy and Cleanup Blog Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - 'data/articles/**'
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if articles directory is empty
        id: check_articles
        run: |
          if [ -z "$(ls -A data/articles)" ]; then
            echo "No files in data/articles. Skipping the workflow."
            exit 0
          fi

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup commit description
        env:
          RUN_URL: "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
          HEAD_COMMIT_URL: "${{ github.event.repository.html_url }}/commit/${{ github.event.after || github.sha }}"
        id: setup_description
        run: |
          DESCRIPTION=$(cat <<EOF
          Add and Clean Up Blog Markdown Files

          created from ${{ env.RUN_URL }}
          latest commit: ${{ env.HEAD_COMMIT_URL }}
          EOF)
          DESCRIPTION="${DESCRIPTION//$'\n'/'%0A'}"
          echo "::set-output name=content::$DESCRIPTION"

      - name: Copy New Blog Markdown File
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        if: steps.check_articles.outputs.success != 'false'
        env:
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: "data/articles/"
          destination_repo: ${{ vars.DESTINATION_REPO }}
          destination_folder: "/"
          destination_branch: ${{ vars.DESTINATION_REPO_HEAD_BRANCH }}
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: ${{ steps.setup_description.outputs.content }}

      - name: Delete Blog Markdown Files
        if: steps.check_articles.outputs.success != 'false'
        run: |
          rm -rf data/articles/*
        shell: bash

      - name: Commit Deleted Blog Files
        if: steps.check_articles.outputs.success != 'false'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/articles/
          git commit -m "Delete all blog markdown files after copying"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to another-repo
        if: steps.check_articles.outputs.success != 'false'
        run: |
          gh pr create \
            --title "Add and Clean Up Blog Markdown files" \
            --body "${{ steps.setup_description.outputs.content }}" \
            --repo "${{ vars.DESTINATION_REPO }}" \
            --base "${{ vars.DESTINATION_REPO_BASE_BRANCH }}" \
            --head "${{ vars.DESTINATION_REPO_HEAD_BRANCH }}" \
            --reviewer "${{ github.event.head_commit.committer.username || github.triggering_actor }}"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
